---
title: "Private elementary and secondary schools revenues"
author: "Percy Kamba"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(ggplot2)
```

##Load and clean data


```{r}
# Download the dataset
temp_file <- tempfile()
download.file("https://www150.statcan.gc.ca/n1/tbl/csv/37100084-eng.zip", temp_file)
private_data <- read_csv(unz(temp_file, "37100084.csv"))
unlink(temp_file)  # Remove temp file

# Organize data
private <- private_data %>%
  mutate(Year = as.Date(paste0(substr(REF_DATE, 1, 4), "-01-01"))) %>%
  rename(Revenue = VALUE) %>%
  select(Year, Revenue)
```
```{r}
summary(private)
```
##plot the revenu trends over the years

```{r}
ggplot(private, aes(x = Year, y = Revenue)) +
  geom_col(fill = "black") +
  ggtitle("Private School Revenues from Board & Lodging Fees") +
  labs(x = "Year", y = "Revenue (CAD)") +
  theme_minimal()
```

## Revenue trends per provinceover the years

```{r}
funding_trends <- private_data %>%
  mutate(Date = as.Date(paste0(substr(REF_DATE, 1, 4), "-01-01"))) %>%
  filter(GEO != "Canada") %>%  # Remove national total
  group_by(Date, GEO) %>%
  summarise(TotalFunding = sum(VALUE, na.rm = TRUE)) %>%
  ungroup()

ggplot(funding_trends, aes(x = Date, y = TotalFunding, color = GEO)) +
  geom_line(size = 1) +
  labs(title = "Private School Revenues by Province Over Time",
       x = "Year",
       y = "Revenue (CAD)",
       color = "Province") +
  theme_minimal()


```
